import {StyleSheet} from 'react-native';
import {FONT, SIZES, COLORS, SHADOWS} from '../../../constants/theme';

export const styles = StyleSheet.create({
  mainStyle: {backgroundColor: COLORS.white, height: '100%'},
  container: {
    paddingLeft: 10,
    paddingRight: 10,
  },
  header: {
    alignItems: 'center',
    paddingTop: 20,
    paddingBottom: 20,
    gap: 20,
  },
  toolbarContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
    paddingTop: 4,
    paddingBottom: 10,
    paddingRight: 10,
    paddingLeft: 10,
  },
  btnToolBar: (width = 46) => ({
    width: width,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: COLORS.grey,
  }),
  image: width => ({
    width: width,
    height: width,
    borderRadius: width / 3,
  }),
  userName: {
    fontFamily: FONT.regular,
    fontSize: SIZES.large,
    color: COLORS.secondary,
  },
  welcomeMessage: {
    fontFamily: FONT.bold,
    fontSize: SIZES.xLarge,
    color: COLORS.primary,
    marginTop: 2,
    marginBottom: 10,
  },
  searchContainer: {
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'row',
    height: 50,
  },
  searchWrapper: {
    flex: 1,
    backgroundColor: COLORS.grey,
    marginRight: SIZES.small,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: SIZES.medium,
    height: '100%',
  },
  searchInput: {
    fontFamily: FONT.regular,
    width: '100%',
    height: '100%',
    paddingHorizontal: SIZES.medium,
  },
  searchBtn: {
    width: 50,
    height: '100%',
    backgroundColor: COLORS.tertiary,
    borderRadius: SIZES.medium,
    justifyContent: 'center',
    alignItems: 'center',
  },
  searchBtnImage: {
    width: '50%',
    height: '50%',
    tintColor: COLORS.white,
  },
  content: {gap: 20, marginRight: 10, marginLeft: 10},
  contentChild: {flexDirection: 'row', gap: 10},
  btnOnMap: {
    backgroundColor: COLORS.secondary,
    borderRadius: 4,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  txtOnMap: {color: COLORS.white, fontFamily: FONT.medium},
  btnEdit: {
    width: 100,
    backgroundColor: COLORS.gray,
    borderRadius: 4,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  btnBack: {
    position: 'absolute',
    zIndex: 999,
    margin: 10,
    borderRadius: 54,
    padding: 8,
    backgroundColor: COLORS.white,
    ...SHADOWS.small,
  },
  modalCtnr: {
    backgroundColor: 'rgba(0,0,0,0.8)',
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalContent: width => ({
    backgroundColor: COLORS.white,
    width: width * 0.9,
    padding: 10,
    gap: 10,
  }),
  txtTitle: {
    fontFamily: FONT.regular,
    fontSize: 16,
    alignSelf: 'center',
  },
  rowCtnr: {
    flexDirection: 'row',
    gap: 10,
    alignItems: 'center',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: COLORS.gray2,
    paddingLeft: 14,
  },
  btnCtnr: {
    flexDirection: 'row',
    gap: 10,
    justifyContent: 'center',
    marginTop: 20,
  },
  btnSave: {
    backgroundColor: COLORS.tertiary,
    borderRadius: 4,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 10,
  },
  txtSave: {color: COLORS.white, fontFamily: FONT.medium},
  btnCancel: {
    backgroundColor: COLORS.gray2,
    borderRadius: 4,
    padding: 10,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
    flexDirection: 'row',
    gap: 10,
  },
});
